INSERT INTO towns (code, location)
VALUES
 ('CA','Cape Town'),
 ('CAR','Clanwilliam & Lamberts Bay'),
 ('CAW','George'),
 ('CBL','Ladismith'),
 ('CBM','Laingsburg'),
 ('CBR','Montagu'),
 ('CBS','Mossel Bay & Hartenbos'),
 ('CBT','Murraysburg'),
 ('CBY','Piketberg'),
 ('CCA','Prince Albert'),
 ('CCC','Riversdale & Still Bay'),
 ('CCD','Robertson & McGregor'),
 ('CCK','Swellendam & Barrydale'),
 ('CCM','Tulbagh'),
 ('CCO','Uniondale'),
 ('CCP','Vanrhynsdorp & Klawer'),
 ('CEA','Moorreesburg'),
 ('CEG','Heidelberg'),
 ('CEM','Hermanus, Gans Bay, Onrus River & Stanford'),
 ('CEO','Grabouw'),
 ('CER','Bonnievale'),
 ('CES','Albertinia'),
 ('CEX','Porterville'),
 ('CEY','Strand & Gordons Bay'),
 ('CFM','Wolseley'),
 ('CFG','Vredenburg & St Helena Bay'),
 ('CER','Somerset West'),
 ('CFP','Velddrif'),
 ('CFR','Kuilsrivier & Brackenfell'),
 ('CG','Oudtshoorn'),
 ('CJ','Paarl & Franschhoek'),
 ('CK','Malmesbury & Darling'),
 ('CL','Stellenbosch'),
 ('CN','Wellington'),
 ('CO','Calitzdorp'),
 ('CR','Hopefield & Langebaan'),
 ('CS','Bredasdorp & Napier'),
 ('CT','Ceres'),
 ('CV','Vredendal'),
 ('CW','Worcester, De Doorns & Touwsrivier'),
 ('CX','Knysna, Sedgefield & Plettenberg Bay'),
 ('CY','Bellville, Durbanville & Kraaifontein'),
 ('CZ','Beaufort West');
